on:
  script:
    run: |
      var result = await helpers.axios.get("https://${{secrets.IZ_ID}}-iz.impfterminservice.de/rest/suche/termincheck?plz=${{secrets.PLZ}}&leistungsmerkmale=${{secrets.IMPFSTOFFE}}");
      result.data.hash = Date.now();
      return Array.of(result.data);
jobs:
  print:
    name: Notify
    if: ${{ on.script.outputs.termineVorhanden }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Es sind Impftermine vorhanden"
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Impftermincheck: Es sind Impftermine verfügbar!"
          body: "Es sind Impftermine verfügbar!"
          to: ${{secrets.MAIL_RECIPIENTS}}
          from: Impftermincheck
